SELECT SUM(SALEPRICE) FROM PETSALE;

SELECT SUM(SALEPRICE) AS SUM_OF_SALEPRICE FROM PETSALE;

SELECT MAX(QUANTITY) FROM PETSALE;

SELECT MIN(ID) FROM PETSALE WHERE ANIMAL = 'Dog';

SELECT AVG(SALEPRICE) FROM PETSALE WHERE ANIMAL = 'Dog';

SELECT AVG(QUANTITY) FROM PETSALE WHERE ANIMAL = 'Dog';

SELECT AVG(SALEPRICE / QUANTITY) FROM PETSALE WHERE ANIMAL = 'Dog';

SELECT ROUND(SALEPRICE) FROM PETSALE;

SELECT LENGTH(ANIMAL) FROM PETSALE;

SELECT UCASE(ANIMAL) FROM PETSALE;

SELECT * FROM PETSALE WHERE LCASE(ANIMAL) = 'cat';

SELECT DISTINCT(UCASE(ANIMAL)) FROM PETSALE;

SELECT DAY(SALEDATE) FROM PETSALE WHERE ANIMAL='Cat';

SELECT COUNT(*) FROM PETSALE WHERE MONTH(SALEDATE) = '05';

SELECT (SALEDATE + 3 DAYS) FROM PETSALE;

SELECT (CURRENT_DATE - SALEDATE) FROM PETSALE;